In [1]:
import transformers

from transformers import AutoModel, AutoTokenizer, BertTokenizer
MODEL_NAME = 'distilbert-base-uncased'

model = AutoModel.from_pretrained(MODEL_NAME)
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model2 = AutoModel.from_pretrained('bert-base-uncased')
tokenizer2 = AutoTokenizer.from_pretrained('bert-base-uncased')

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_layer_norm.weight', 'vocab_projector.weight', 'vocab_transform.weight', 'vocab_projector.bias', 'vocab_transform.bias', 'vocab_layer_norm.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.

In [18]:
tokenizer.convert_ids_to_tokens(tokenizer('임베딩귉')['input_ids']) ### unkknown도 분명있다 찾기 힘들뿐. 

['[CLS]', '[UNK]', '[SEP]']

In [3]:
text = '이순신은 조선 중기의 무신이다.'
text2 = '나는 강아지다'
text3 = '그의 이름은 최수빈인 것 같기도 하고 아닌것 같기도 하다. '
batch_text = [text, text2]

In [4]:
tokenizer.special_tokens_map

{'unk_token': '[UNK]',
 'sep_token': '[SEP]',
 'pad_token': '[PAD]',
 'cls_token': '[CLS]',
 'mask_token': '[MASK]'}

In [6]:
tokenizer.unk_token

'[UNK]'

In [12]:
print(tokenizer.encode(text))  ## encode는 그저 input_ids만 출력해주고
print(tokenizer.encode_plus(text)) ## encode_plus는 마스킹 등 모두 출력해준다. 
print(tokenizer(text)) ## 보니까 __call__ 함수는 똑같은 것 같다. encode_plus

[101, 1463, 30019, 29997, 30014, 30021, 29997, 30019, 30021, 29999, 30017, 30021, 1464, 30011, 29997, 30008, 30021, 1464, 30014, 30025, 29991, 30019, 29999, 30018, 1459, 30014, 29997, 30019, 30021, 29999, 30019, 29993, 30006, 1012, 102]
{'input_ids': [101, 1463, 30019, 29997, 30014, 30021, 29997, 30019, 30021, 29999, 30017, 30021, 1464, 30011, 29997, 30008, 30021, 1464, 30014, 30025, 29991, 30019, 29999, 30018, 1459, 30014, 29997, 30019, 30021, 29999, 30019, 29993, 30006, 1012, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
{'input_ids': [101, 1463, 30019, 29997, 30014, 30021, 29997, 30019, 30021, 29999, 30017, 30021, 1464, 30011, 29997, 30008, 30021, 1464, 30014, 30025, 29991, 30019, 29999, 30018, 1459, 30014, 29997, 30019, 30021, 29999, 30019, 29993, 30006, 1012, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [13]:
## 2개의 text를 넣을때는 이렇게 padding혹은 truncate을 해주어야 한다. 안 그러면 에러가 남. 
## 밑에서 각각의 text input계산은 잘 하던데 한번에 배치로 처리하라때는 길이를 맞추어줘야하는듯하다.

print(tokenizer(text, return_tensors='pt'))
print(tokenizer(batch_text, return_tensors='pt', padding=True)) ## 이렇게 하면 batch 단위로 padding이 된다. 

{'input_ids': tensor([[  101,  1463, 30019, 29997, 30014, 30021, 29997, 30019, 30021, 29999,
         30017, 30021,  1464, 30011, 29997, 30008, 30021,  1464, 30014, 30025,
         29991, 30019, 29999, 30018,  1459, 30014, 29997, 30019, 30021, 29999,
         30019, 29993, 30006,  1012,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
{'input_ids': tensor([[  101,  1463, 30019, 29997, 30014, 30021, 29997, 30019, 30021, 29999,
         30017, 30021,  1464, 30011, 29997, 30008, 30021,  1464, 30014, 30025,
         29991, 30019, 29999, 30018,  1459, 30014, 29997, 30019, 30021, 29999,
         30019, 29993, 30006,  1012,   102],
        [  101,  1456, 30006, 29992, 30017, 30021,  1455, 30006, 30025, 29999,
         30006, 30000, 30019, 29993, 30006,   102,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,   

In [15]:
print(model(**tokenizer(text, return_tensors='pt'))['last_hidden_state'].shape)  ## 1, 35,768
print(model(**tokenizer(text2, return_tensors='pt'))['last_hidden_state'].shape)  ## 1, 16, 768
print(model(**tokenizer(batch_text, return_tensors='pt', padding=True))['last_hidden_state'].shape) ## 2,35, 768

## BERT 모델의 경우에는 어떤 입력을 넣어도 입력에 해당하는 길이만큼만 뱉어준다.
## 즉, 한개의 입력을 넣을때는 bert모델 학습시킬때 썼던 뭐..최대길이 이런걸 맞춰줄 필요가 없다. 이건 알아보니 self attention이 dot product로 되어있어서
## 굳이 안맞추어도 길이가 다른것들도 학습이 가능하고 prediction도 가능하다고 한다. 
## ** 이거 안해주면 에러난다.

torch.Size([1, 35, 768])
torch.Size([1, 16, 768])
torch.Size([2, 35, 768])


In [24]:
## 두 문장을 넣을때는 다음과 같다. 
tokenizer('나는 최수빈이다 그럴까?', '나는 호랑이다', return_token_type_ids=True)

{'input_ids': [101, 1456, 30006, 29992, 30017, 30021, 100, 100, 1029, 102, 1456, 30006, 29992, 30017, 30021, 1469, 30011, 29994, 30006, 30025, 29999, 30019, 29993, 30006, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [17]:
tokenizer2('나는 최수빈이다 그럴까?', '나는 호랑이다', return_token_type_ids=False)

{'input_ids': [101, 1456, 30006, 29992, 30017, 30021, 100, 100, 1029, 102, 1456, 30006, 29992, 30017, 30021, 1469, 30011, 29994, 30006, 30025, 29999, 30019, 29993, 30006, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [47]:
model2(**tokenizer2('나는 최수빈이다 그럴까?', '나는 호랑이다', return_token_type_ids=True, return_tensors='pt'))
### token_type_ids를 True, False했을때 결과가 다르다. token_type_ids를 False로 하면 다 0으로 채워서 주는듯하다. 

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-1.1219,  0.1607, -0.9875,  ..., -0.5183,  0.8429, -0.0204],
         [-0.6121, -0.3777, -0.7107,  ...,  0.2729,  1.2838, -0.2153],
         [-0.8598, -0.2312, -0.2313,  ..., -0.1878,  0.0265, -0.9636],
         ...,
         [-0.1241, -0.1569, -0.1264,  ..., -0.2564,  0.0171, -0.6824],
         [-0.5016, -0.1034, -0.2702,  ..., -0.1109,  0.1309, -1.2801],
         [ 0.5553, -0.2568, -0.5277,  ...,  0.0482, -0.3414, -0.3930]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-0.9835, -0.9031, -0.9999,  0.9958,  0.9958, -0.8062,  0.9953,  0.8118,
         -0.9998, -1.0000, -0.9912,  0.9998,  0.9511,  0.9948,  0.9662, -0.9948,
         -0.9805, -0.9207,  0.8079, -0.9715,  0.9490,  1.0000, -0.9515,  0.8374,
          0.9202,  1.0000, -0.9894,  0.9171,  0.9684,  0.6693, -0.9870,  0.8270,
         -0.9666, -0.8135, -0.9999, -0.9982,  0.9418, -0.8669, -0.7864, -0.6617,
         -0.9328,  0.8663,  1.00

In [18]:
model2  ## bert model 구조 잘 살펴보면 word 임베딩, position 임베딩, token type 임베딩 3개가 있다. , 2,768이라는건 0과 1 을 의미하는 거일테고.. 
model ## token type 임베딩 자체가 distilber는 없다. 

DistilBertModel(
  (embeddings): Embeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (transformer): Transformer(
    (layer): ModuleList(
      (0): TransformerBlock(
        (attention): MultiHeadSelfAttention(
          (dropout): Dropout(p=0.1, inplace=False)
          (q_lin): Linear(in_features=768, out_features=768, bias=True)
          (k_lin): Linear(in_features=768, out_features=768, bias=True)
          (v_lin): Linear(in_features=768, out_features=768, bias=True)
          (out_lin): Linear(in_features=768, out_features=768, bias=True)
        )
        (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (ffn): FFN(
          (dropout): Dropout(p=0.1, inplace=False)
          (lin1): Linear(in_features=768, out_features=3072, bias=True)
          (lin2): Linear(i

In [19]:
model(**tokenizer('나는 최수빈이다 그럴까?', '나는 호랑이다', return_token_type_ids=True, return_tensors='pt'))
## 이렇게하면 에러가 뜨는게 당연 , DISTILBERT는 TOKEN_TYPE_IDS가 없다. 

TypeError: forward() got an unexpected keyword argument 'token_type_ids'

In [21]:
from transformers import AutoModelForSequenceClassification
## 이건 label조절 불가 무조건 2개 인듯하다. 
## 어쩌면 학습된 모델에 classification만 붙인것일수도 있겠다.. classifier의 경우는 random하게.. weight초기화된 걸 붙인것인듯하다. 찾아보니 그렇게 나온다. 
## 단톡방에 물어보니까 fine-tuning한것도 제공한다고 한다. 

model = AutoModelForSequenceClassification.from_pretrained(
    pretrained_model_name_or_path='distilbert-base-uncased')

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertForSequenceClassification: ['vocab_transform.bias', 'vocab_transform.weight', 'vocab_projector.bias', 'vocab_layer_norm.bias', 'vocab_projector.weight', 'vocab_layer_norm.weight']
- This IS expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.weight', 'pre_classifier.bias', 'pre_classi

In [22]:
model

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0): TransformerBlock(
          (attention): MultiHeadSelfAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
       

In [24]:
model.eval()
model(**tokenizer(text, return_tensors='pt'))

SequenceClassifierOutput(loss=None, logits=tensor([[-0.0243,  0.1185]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [25]:
model.distilbert
model.classifier 
## 이렇게 두개로 나눠져있어서 freeze할 수 있다. 

for param in model.distilbert.parameters():
    param.requires_grad = False
    
## model에서 distilbert부분은 freeze하는것. 

In [26]:
## 학습전. 
print(model.classifier.state_dict()['weight'])
print(model.classifier.state_dict()['bias'])

model.distilbert.state_dict().keys() ## 모든 layer 이름.
## pytorch에서는 state_dict로 모델 layer이름 가중치 bias에 모두 접근할 수 있다. 

print(model.distilbert.state_dict()['embeddings.word_embeddings.weight'])
print(model.distilbert.state_dict()['transformer.layer.0.attention.q_lin.weight'])

tensor([[-0.0315, -0.0085, -0.0348,  ...,  0.0207,  0.0239,  0.0078],
        [ 0.0098, -0.0099,  0.0116,  ..., -0.0058, -0.0259,  0.0040]])
tensor([0., 0.])
tensor([[-0.0166, -0.0666, -0.0163,  ..., -0.0200, -0.0514, -0.0264],
        [-0.0132, -0.0673, -0.0161,  ..., -0.0227, -0.0554, -0.0260],
        [-0.0176, -0.0709, -0.0144,  ..., -0.0246, -0.0596, -0.0232],
        ...,
        [-0.0231, -0.0588, -0.0105,  ..., -0.0195, -0.0262, -0.0212],
        [-0.0490, -0.0561, -0.0047,  ..., -0.0107, -0.0180, -0.0219],
        [-0.0065, -0.0915, -0.0025,  ..., -0.0151, -0.0504,  0.0460]])
tensor([[-0.0024,  0.0224, -0.0207,  ...,  0.0200,  0.0560,  0.0463],
        [ 0.0080,  0.0269, -0.0575,  ..., -0.0221,  0.1373,  0.0125],
        [-0.0043,  0.0318,  0.0189,  ..., -0.0107,  0.0083, -0.0422],
        ...,
        [ 0.0120, -0.0023,  0.0710,  ...,  0.0636,  0.0457, -0.0321],
        [ 0.0061,  0.0861,  0.0829,  ..., -0.0218,  0.1167,  0.0146],
        [-0.0096, -0.0904,  0.0143,  ..., -0.

In [28]:
import torch
model.train()

for i in range(100):
    logits = model(**tokenizer(text, return_tensors='pt'))
    optimizer = torch.optim.Adam(model.parameters(), lr = 0.01)
    loss = torch.nn.functional.nll_loss(logits['logits'], torch.LongTensor([1]))
    loss.backward()
    optimizer.step()
    print(i)
 

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [29]:
## 학습후
model.eval()
print(model.classifier.state_dict()['weight'])
print(model.classifier.state_dict()['bias'])

model.distilbert.state_dict().keys() ## 모든 layer 이름.
## pytorch에서는 state_dict로 모델 layer이름 가중치 bias에 모두 접근할 수 있다. 

print(model.distilbert.state_dict()['embeddings.word_embeddings.weight'])
print(model.distilbert.state_dict()['transformer.layer.0.attention.q_lin.weight'])


### 학습하니 바뀌는 것을 확인할 수 있따. 하지만 weight freeze한 부분에서는 안 변하는 것도 확인할 수 있다. 

tensor([[-0.0315, -0.0085, -0.0348,  ...,  0.0207,  0.0239,  0.0078],
        [ 1.0098,  0.9801,  0.7216,  ...,  0.9842,  0.9741,  1.0040]])
tensor([0.0000, 1.0000])
tensor([[-0.0166, -0.0666, -0.0163,  ..., -0.0200, -0.0514, -0.0264],
        [-0.0132, -0.0673, -0.0161,  ..., -0.0227, -0.0554, -0.0260],
        [-0.0176, -0.0709, -0.0144,  ..., -0.0246, -0.0596, -0.0232],
        ...,
        [-0.0231, -0.0588, -0.0105,  ..., -0.0195, -0.0262, -0.0212],
        [-0.0490, -0.0561, -0.0047,  ..., -0.0107, -0.0180, -0.0219],
        [-0.0065, -0.0915, -0.0025,  ..., -0.0151, -0.0504,  0.0460]])
tensor([[-0.0024,  0.0224, -0.0207,  ...,  0.0200,  0.0560,  0.0463],
        [ 0.0080,  0.0269, -0.0575,  ..., -0.0221,  0.1373,  0.0125],
        [-0.0043,  0.0318,  0.0189,  ..., -0.0107,  0.0083, -0.0422],
        ...,
        [ 0.0120, -0.0023,  0.0710,  ...,  0.0636,  0.0457, -0.0321],
        [ 0.0061,  0.0861,  0.0829,  ..., -0.0218,  0.1167,  0.0146],
        [-0.0096, -0.0904,  0.0143,  

In [30]:
torch.nn.functional.softmax(model(**tokenizer(text, return_tensors='pt'))['logits'])

C:\Users\chkim\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


tensor([[0., 1.]], grad_fn=<SoftmaxBackward0>)

In [31]:
torch.nn.functional.softmax(torch.Tensor([0.0435, 0.0877]))

C:\Users\chkim\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


tensor([0.4890, 0.5110])